POST http://localhost:8080/engine-rest/process-definition/key/DaNegociacaoAEntregaDoPedidoProcess/start
Content-Type: application/json

{
	"variables": {
		"quantidadePedida": {
			"value": 100,
			"type": "Integer"
		},
		"prazoPedido": {
			"value": 1,
			"type": "Integer"
		},
		"nomeCliente": {
			"value": "Creusa",
			"type": "String"
		},
		"indicacao": {
			"value": true,
			"type": "Boolean"
		},
		"comprou": {
			"value": true,
			"type": "Boolean"
		},
		"pagou": {
			"value": true,
			"type": "Boolean"
		}
	},
	"withVariablesInReturn": true
}